- name: Install nginx and update cache
  apt:
    name: nginx
    state: latest
- name: Copy default with ansible to web server
  ansible.builtin.copy:
    src: roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify:
  - restart nginx
- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes