- name: Install nginx and update cache
  apt:
    name: nginx
    state: latest
- name: Copy default.j2 with ansible to web server
  template:
    src: roles/nginx/templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
  - restart nginx
- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes