---
- name: Download influxdb_stats_exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_386
    dest: /usr/local/bin/prometheus-influxdb-stats-exporter
    mode: '0770'
    owner: prometheus
  notify:
    - restart prometheus-influxdb-stats-exporter

- name: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  template:
    src: influxdb-stats-exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify:
  - restart prometheus-influxdb-stats-exporter

- name: start influxdb_exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes
