- name: Add a grafana signing key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add grafana repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana.list

- name: Install grafana
  apt:
    name: grafana
  notify:
  - update grafana
  - reset password

- name: Start service grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- template:
    src: datasources.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
  notify: restart grafana

- template:
    src: datasourcesINFLUX.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasourcesINFLUX.yaml
  notify: restart grafana

- template:
    src: datasourcesTELEGRAF.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasourcesTELEGRAF.yaml
  notify: restart grafana

- name: Copy dashboards.yaml
  ansible.builtin.copy:
    src: dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/

- name: Copy dashboardsTELEGRAF.yaml
  ansible.builtin.copy:
    src: dashboardsTELEGRAF.yaml
    dest: /etc/grafana/provisioning/dashboards/

- name: Copy main.json
  ansible.builtin.copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/
  notify: restart grafana

- name: Copy mainSyslog.json
  ansible.builtin.copy:
    src: mainSyslog.json
    dest: /var/lib/grafana/dashboards/
  notify: restart grafana
