- name: Grafana directory
  ansible.builtin.file:
    name: /opt/grafana
    state: directory

- name: Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true

- name: Creating grafana provisioning directories
  ansible.builtin.file:
    name: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - dashboards
    - datasources

- name: Creating grafana dashboards
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  loop:
    - dashboards.yaml
    - dashboardsTELEGRAF.yaml
    - main.json
    - mysql.json
    - syslog.json

- template:
    src: datasources.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasources.yaml

- template:
    src: datasourcesINFLUX.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasourcesINFLUX.yaml

- template:
    src: datasourcesTELEGRAF.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasourcesTELEGRAF.yaml

- name: Grafana Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: always
