- name: install uWSGI packages
  apt: 
    name: uwsgi
    state: latest

- name: install uWSGI plugin
  apt:
    name: uwsgi-plugin-python3
    state: latest

- name: Template a file to /etc/uwsgi/apps-enabled/agama.ini
  ansible.builtin.template:
    src: roles/uwsgi/templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    group: agama
    mode: '755'
  notify:
  - restart uwsgi

- name: start uWSGI service
  ansible.builtin.service:
    name: uwsgi
    enabled: yes
    state: started

- name: stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
