{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "haproxy_server_up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "HAproxy status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "keepalived state ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "[[tag_dst]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kifydb",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{ instance  }}" }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up\n\n", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Amount of  http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Mysql amount of selects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bind9 ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "A DNS query amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "rate(bind_resolver_query_retries_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}