{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Mysql amount of selects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])\n"
    }
   ]
  },
  {
   "title": "MySQL server ids",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "Mysql read only status ",
   "type": "stat",
   "description": "Historical data for MySQL server read only status",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "MySQL replica  IO thread",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "MySQL replica SQL thread(Slave)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  }
 ]
}