- name: create a directory
  ansible.builtin.file:
    path: /opt/agama 
    owner: agama
    group: agama
    mode: '0755'
    state: directory
- name: install dependencies
  apt:
    name: python3-flask-sqlalchemy
    state: latest
    update_cache: yes
- name: install agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
    mode: '0755'
  
