- name: Agama directory
  ansible.builtin.file:
    name: /opt/agama
    state: directory

- name: download Agama dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Agama Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{dns_cname_records['mysql1']}}/{{mysql_database}}"
    published_ports: "{{agama_ports[0]}}:8000"

- name: Agama2 Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama2
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{dns_cname_records['mysql1']}}/{{mysql_database}}"
      #AGAMA_DATABASE_URI: "mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}"
    published_ports: "{{agama_ports[1]}}:8000"
