- name: create a directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    owner: backup
    group: backup
    mode: '0755'
    state: directory

- template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
