- name: install keepalived
  apt:
    name: keepalived

- name: keepalived_script user
  user:
    name: keepalived_script

- template:
    src: keepalived_script.j2
    dest: /usr/local/bin/keepalived_script
    mode: 0770
    owner: keepalived_script
    group: keepalived_script
  notify: restart keepalived

- name: /etc/keepalived/keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Start service keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes
