---
- name: prometheus package install
  apt:
    name: prometheus
    state: latest
- template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify:
    - restart prometheus
- template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - restart prometheus

- name: Start service prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
