- name: update grafana
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: restart grafana
  service:
    name: grafana-server
    state: restarted

- name: reset password
  shell: |
    sleep 30
    grafana-cli admin reset-admin-password {{grafana_pass}}
  no_log: true
