- name: Docker package
  apt:
    name:
      - docker.io
      - python3-docker

- name: Log into DockerHub
  docker_login:
    username: hapukoor
    password: "{{ docker_acc_pass }}"
  no_log: True

- name: Docker service
  service:
    name: docker
    state: started
    enabled: yes
