global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default.j2 is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: prometheus/metrics # defaults to '/metrics'
    static_configs:
      - targets: ['localhost:{{ prometheus_port }}']

  - job_name: node
    static_configs:
      - targets: ['localhost:{{ prometheus_exporter_node_port }}']

  - job_name: linux
    static_configs:
      - targets:
{% for vm in vms %}
        - {{ vm }}:{{ prometheus_exporter_node_port }}
{% endfor %}

  - job_name: bind9
    static_configs:
      - targets:
{% for vm in groups['dns_servers'] %}
        - {{ vm }}:{{ prometheus_exporter_bind_port }}
{% endfor %}

  - job_name: mysql
    static_configs:
      - targets:
{% for vm in groups['db_servers'] %}
        - {{ vm }}:{{ prometheus_exporter_mysql_port }}
{% endfor %}

  - job_name: nginx
    static_configs:
      - targets:
{% for vm in groups['all'] %}
        - {{ vm }}:{{ prometheus_exporter_nginx_port }}
{% endfor %}

  - job_name: influxdb
    static_configs:
      - targets:
{% for vm in groups['influxdb'] %}
        - {{ vm }}:{{ prometheus_exporter_influxdb_port }}
{% endfor %}

  - job_name: haproxy
    static_configs:
      - targets:
{% for vm in groups['haproxy'] %}
        - {{ vm }}:{{ haproxy_port }}
{% endfor %}

  - job_name: keepalived
    static_configs:
      - targets:
{% for vm in groups['haproxy'] %}
        - {{ vm }}:{{ prometheus_exporter_keepalived_port }}
{% endfor %}
