global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default.j2 is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: prometheus/metrics # defaults to '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

  - job_name: linux
    static_configs:
      - targets:
{% for vm in vms %}
        - {{ vm }}:9100
{% endfor %}

  - job_name: bind9
    static_configs:
      - targets:
{% for vm in groups['dns_servers'] %}
        - {{ vm }}:9119
{% endfor %}

  - job_name: mysql
    static_configs:
      - targets:
{% for vm in groups['db_servers'] %}
        - {{ vm }}:9104
{% endfor %}

  - job_name: nginx
    static_configs:
      - targets:
{% for vm in groups['all'] %}
        - {{ vm }}:9113
{% endfor %}

  - job_name: influxdb
    static_configs:
      - targets:
{% for vm in groups['influxdb'] %}
        - {{ vm }}:9424
{% endfor %}
